SUBROUTINE llmr_pattern_applied_cloudsc(KLON, KLEV, NCLV, NCLDTOP, NCLDQV, &
  & ZTP1, PAPH, PAP, ZDQSMIXDT, ZANEWM1, ZDQS, ZLCUST, ZEVAPLIMMIX, &
  & ZLFINALSUM, ZSOLQA, ZACUST, ZSOLAC, ZDP, PMFU, PMFD, PVERVEL, &
  & PHRSW, PHRLW, ZLDEFR, ZQSMIX, ZQOLD, ZTOLD, LLFLAG, LLFALL, IPHASE, &
  & ZRDCP, JPRB, ZEPSEC, ZQTMST, RG, PTSPHY, RALFDCP, JK) BIND(C, NAME="llmr_pattern_applied_cloudsc")
  
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  
  ! Dimension parameters
  INTEGER(C_INT), VALUE, INTENT(IN) :: KLON, KLEV, NCLV, NCLDTOP, NCLDQV, JK
  
  ! Scalar constants
  REAL(C_DOUBLE), VALUE, INTENT(IN) :: ZRDCP, JPRB, ZEPSEC, ZQTMST, RG, PTSPHY, RALFDCP
  
  ! 1D arrays (horizontal)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZANEWM1(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZDQS(KLON)
  REAL(C_DOUBLE), INTENT(IN)    :: ZDQSMIXDT(KLON)
  REAL(C_DOUBLE), INTENT(IN)    :: ZEVAPLIMMIX(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZLFINALSUM(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZACUST(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZSOLAC(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZDP(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZLDEFR(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZQOLD(KLON)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZTOLD(KLON)
  INTEGER(C_INT), INTENT(INOUT) :: LLFLAG(KLON)
  
  ! 2D arrays (horizontal x vertical/species) - REDUCED DIMENSIONS
  REAL(C_DOUBLE), INTENT(INOUT) :: ZTP1(KLON, 2)      ! Only 2 levels: 0=JK-1, 1=JK
  REAL(C_DOUBLE), INTENT(IN)    :: PAP(KLON, 2)       ! Only 2 levels: 0=JK-1, 1=JK
  REAL(C_DOUBLE), INTENT(IN)    :: PAPH(KLON, KLEV+1)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZLCUST(KLON, NCLV)
  REAL(C_DOUBLE), INTENT(IN)    :: PMFU(KLON, 2)      ! Only 2 levels: 0=JK, 1=JK+1
  REAL(C_DOUBLE), INTENT(IN)    :: PMFD(KLON, 2)      ! Only 2 levels: 0=JK, 1=JK+1
  REAL(C_DOUBLE), INTENT(IN)    :: PVERVEL(KLON, KLEV)
  REAL(C_DOUBLE), INTENT(IN)    :: PHRSW(KLON, KLEV)
  REAL(C_DOUBLE), INTENT(IN)    :: PHRLW(KLON, KLEV)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZQSMIX(KLON, KLEV)
  
  ! 3D arrays (microphysics matrices)
  REAL(C_DOUBLE), INTENT(INOUT) :: ZSOLQA(KLON, NCLV, NCLV)
  
  ! 1D arrays (species properties)
  INTEGER(C_INT), INTENT(IN)    :: LLFALL(NCLV)
  INTEGER(C_INT), INTENT(IN)    :: IPHASE(NCLV)
  
  ! Local variables
  INTEGER(C_INT) :: JL, JM
  REAL(C_DOUBLE) :: ZDTDP, ZDTFORC, ZLFINAL, ZEVAP, ZDPMXDT, ZMFDN
  REAL(C_DOUBLE) :: ZWTOT, ZZZDT, ZDTDIAB
  
  INTEGER(C_INT) :: IDX_PREV, IDX_CURR

  IDX_PREV = MOD(JK - 1, 2)+1
  IDX_CURR = MOD(JK, 2)+1

  ! Function body with logical conversions
  IF (JK > NCLDTOP) THEN
    ! Line offset 1172
    DO JL=1,KLON
      ZDTDP = ZRDCP*0.5_C_DOUBLE*(ZTP1(JL,IDX_PREV) + ZTP1(JL,IDX_CURR)) / PAPH(JL,JK)
      ZDTFORC = ZDTDP*(PAP(JL,IDX_CURR) - PAP(JL,IDX_PREV))
      ZDQS(JL) = ZANEWM1(JL)*ZDTFORC*ZDQSMIXDT(JL)
    ENDDO
    
    ! Line offset 1178
    DO JM=1,NCLV
      IF (LLFALL(JM) == 0 .AND. IPHASE(JM) > 0) THEN
        DO JL=1,KLON
          ZLFINAL = MAX(0.0_C_DOUBLE, ZLCUST(JL,JM) - ZDQS(JL))
          ZEVAP = MIN((ZLCUST(JL,JM) - ZLFINAL), ZEVAPLIMMIX(JL)) 
          ZLFINAL = ZLCUST(JL,JM) - ZEVAP 
          ZLFINALSUM(JL) = ZLFINALSUM(JL) + ZLFINAL
          ZSOLQA(JL,JM,JM) = ZSOLQA(JL,JM,JM) + ZLCUST(JL,JM)
          ZSOLQA(JL,NCLDQV,JM) = ZSOLQA(JL,NCLDQV,JM) + ZEVAP
          ZSOLQA(JL,JM,NCLDQV) = ZSOLQA(JL,JM,NCLDQV) - ZEVAP
        ENDDO
      ENDIF
    ENDDO
    
    ! Line offset 1195
    DO JL=1,KLON
      IF (ZLFINALSUM(JL) < ZEPSEC) ZACUST(JL) = 0.0_C_DOUBLE
      ZSOLAC(JL) = ZSOLAC(JL) + ZACUST(JL)
    ENDDO
    
    ! Line offset 1288
    DO JL=1,KLON
      ZDTDP = ZRDCP*ZTP1(JL,IDX_CURR) / PAP(JL,IDX_CURR)
      ZDPMXDT = ZDP(JL)*ZQTMST
      ZMFDN = 0.0_C_DOUBLE
      IF (JK < KLEV) ZMFDN = PMFU(JL,JK+1) + PMFD(JL,JK+1)
      ZWTOT = PVERVEL(JL,JK) + 0.5_C_DOUBLE*RG*(PMFU(JL,IDX_CURR) + PMFD(JL,IDX_CURR) + ZMFDN)
      ZWTOT = MIN(ZDPMXDT, MAX(-ZDPMXDT, ZWTOT))
      ZZZDT = PHRSW(JL,JK) + PHRLW(JL,JK)
      ZDTDIAB = MIN(ZDPMXDT*ZDTDP, MAX(-ZDPMXDT*ZDTDP, ZZZDT)) &
                      & *PTSPHY + RALFDCP*ZLDEFR(JL)  
      ZDTFORC = ZDTDP*ZWTOT*PTSPHY + ZDTDIAB
      ZQOLD(JL) = ZQSMIX(JL,JK)
      !ZTOLD(JL) = ZTP1(JL,IDX_CURR)
      ZTP1(JL,IDX_CURR) = ZTP1(JL,IDX_CURR) + ZDTFORC
      ZTP1(JL,IDX_CURR) = MAX(ZTP1(JL,IDX_CURR), 160.0_C_DOUBLE)
      LLFLAG(JL) = 1
    ENDDO
  ENDIF
  
END SUBROUTINE llmr_pattern_applied_cloudsc