! Ice Supersaturation Adjustment

SUBROUTINE ice_supersaturation_adjustment(KIDIA, KFDIA, &
    & ZTP1, ZA, ZQX_NCLDQV, ZQSICE, ZCORQSICE, ZFOKOOP, &
    & ZSOLQA, ZSOLAC, ZQXFG, &
    & RTT, RAMIN, RTHOMO, NSSOPT, RKOOPTAU, PTSPHY, ZEPSEC, &
    & NCLDQL, NCLDQI, NCLDQV, NCLV)

  IMPLICIT NONE
  
  ! Dimensions
  INTEGER, INTENT(IN) :: KIDIA, KFDIA, NCLV
  INTEGER, INTENT(IN) :: NCLDQL, NCLDQI, NCLDQV
  INTEGER, INTENT(IN) :: NSSOPT
  
  ! Input arrays
  REAL(8), INTENT(IN) :: ZTP1(KFDIA)      
  REAL(8), INTENT(IN) :: ZA(KFDIA)        
  REAL(8), INTENT(IN) :: ZQX_NCLDQV(KFDIA)
  REAL(8), INTENT(IN) :: ZQSICE(KFDIA)  
  REAL(8), INTENT(IN) :: ZCORQSICE(KFDIA) 
  REAL(8), INTENT(IN) :: ZFOKOOP(KFDIA)  
  
  ! Constants
  REAL(8), INTENT(IN) :: RTT, RAMIN, RTHOMO, RKOOPTAU, PTSPHY, ZEPSEC
  
  ! Output/InOut arrays
  REAL(8), INTENT(INOUT) :: ZSOLQA(KFDIA, NCLV, NCLV) 
  REAL(8), INTENT(INOUT) :: ZSOLAC(KFDIA)            
  REAL(8), INTENT(INOUT) :: ZQXFG(KFDIA, NCLV)       
  
  ! Local variables
  INTEGER :: JL
  REAL(8) :: ZFAC, ZFACI
  REAL(8) :: ZSUPSAT, ZQP1ENV
  REAL(8) :: ZEPSILON
  
  ZEPSILON = 1.E-14

  DO JL = KIDIA, KFDIA

    IF (ZTP1(JL) >= RTT .OR. NSSOPT == 0) THEN
      ZFAC = 1.0D0
      ZFACI = 1.0D0
    ELSE
      ZFAC = ZA(JL) + ZFOKOOP(JL) * (1.0D0 - ZA(JL))
      ZFACI = PTSPHY / RKOOPTAU
    ENDIF

    IF (ZA(JL) > 1.0D0 - RAMIN) THEN
      ZSUPSAT = MAX((ZQX_NCLDQV(JL) - ZFAC * ZQSICE(JL)) / ZCORQSICE(JL), 0.0D0)
    ELSE
      ZQP1ENV = (ZQX_NCLDQV(JL) - ZA(JL) * ZQSICE(JL)) / &
                MAX(1.0D0 - ZA(JL), ZEPSILON)
      ZSUPSAT = MAX((1.0D0 - ZA(JL)) * (ZQP1ENV - ZFAC * ZQSICE(JL)) / &
                ZCORQSICE(JL), 0.0D0)
    ENDIF 
    
    IF (ZSUPSAT > ZEPSEC) THEN

      IF (ZTP1(JL) > RTHOMO) THEN      
        ZSOLQA(JL, NCLDQL, NCLDQV) = ZSOLQA(JL, NCLDQL, NCLDQV) + ZSUPSAT
        ZSOLQA(JL, NCLDQV, NCLDQL) = ZSOLQA(JL, NCLDQV, NCLDQL) - ZSUPSAT
        ZQXFG(JL, NCLDQL) = ZQXFG(JL, NCLDQL) + ZSUPSAT
      ELSE 
        ZSOLQA(JL, NCLDQI, NCLDQV) = ZSOLQA(JL, NCLDQI, NCLDQV) + ZSUPSAT
        ZSOLQA(JL, NCLDQV, NCLDQI) = ZSOLQA(JL, NCLDQV, NCLDQI) - ZSUPSAT
        ZQXFG(JL, NCLDQI) = ZQXFG(JL, NCLDQI) + ZSUPSAT
      ENDIF

      ZSOLAC(JL) = (1.0D0 - ZA(JL)) * ZFACI

    ENDIF

  ENDDO

END SUBROUTINE ice_supersaturation_adjustment
