! Rain Evaporation (Abel-Boutle scheme)
! 

SUBROUTINE rain_evaporation_abel_boutle(KIDIA, KFDIA, &
    & ZTP1, ZQX_NCLDQV, ZA, ZQSLIQ, ZQXFG_NCLDQR, &
    & ZCOVPTOT, ZCOVPCLR, ZCOVPMAX, ZRHO, PAP, &
    & ZSOLQA, ZEVAP_OUT, &
    & RTT, RV, RD, RPRECRHMAX, RCOVPMIN, RDENSREF, PTSPHY, ZEPSEC, &
    & RCL_FAC1, RCL_FAC2, RCL_CDENOM1, RCL_CDENOM2, RCL_CDENOM3, &
    & RCL_KA273, RCL_CONST1R, RCL_CONST2R, RCL_CONST3R, RCL_CONST4R, &
    & NCLDQV, NCLDQR, NCLV)

  IMPLICIT NONE
  
  ! Dimensions
  INTEGER, INTENT(IN) :: KIDIA, KFDIA, NCLV
  INTEGER, INTENT(IN) :: NCLDQV, NCLDQR
  
  ! Input arrays
  REAL(8), INTENT(IN) :: ZTP1(KFDIA)          
  REAL(8), INTENT(IN) :: ZQX_NCLDQV(KFDIA)    
  REAL(8), INTENT(IN) :: ZA(KFDIA)            
  REAL(8), INTENT(IN) :: ZQSLIQ(KFDIA)        
  REAL(8), INTENT(IN) :: ZRHO(KFDIA)          
  REAL(8), INTENT(IN) :: PAP(KFDIA)           
  
  ! InOut arrays
  REAL(8), INTENT(INOUT) :: ZQXFG_NCLDQR(KFDIA) 
  REAL(8), INTENT(INOUT) :: ZCOVPTOT(KFDIA)      
  REAL(8), INTENT(INOUT) :: ZCOVPCLR(KFDIA)      
  REAL(8), INTENT(IN) :: ZCOVPMAX(KFDIA)         
  
  ! Output arrays
  REAL(8), INTENT(INOUT) :: ZSOLQA(KFDIA, NCLV, NCLV)  
  REAL(8), INTENT(OUT) :: ZEVAP_OUT(KFDIA)             
  
  ! Constants
  REAL(8), INTENT(IN) :: RTT, RV, RD
  REAL(8), INTENT(IN) :: RPRECRHMAX, RCOVPMIN, RDENSREF, PTSPHY, ZEPSEC
  REAL(8), INTENT(IN) :: RCL_FAC1, RCL_FAC2
  REAL(8), INTENT(IN) :: RCL_CDENOM1, RCL_CDENOM2, RCL_CDENOM3
  REAL(8), INTENT(IN) :: RCL_KA273
  REAL(8), INTENT(IN) :: RCL_CONST1R, RCL_CONST2R, RCL_CONST3R, RCL_CONST4R
  
  ! Local variables
  INTEGER :: JL
  REAL(8) :: ZZRH, ZQE, ZPRECLR, ZFALLCORR, ZESATLIQ
  REAL(8) :: ZLAMBDA, ZEVAP_DENOM, ZCORR2, ZKA, ZSUBSAT
  REAL(8) :: ZBETA, ZDENOM, ZDPEVAP, ZEVAP
  LOGICAL :: LLO1
  
  ! Local constants for saturation vapor pressure
  REAL(8) :: R2ES_LOCAL, R3LES_LOCAL, R4LES_LOCAL
  R2ES_LOCAL = 611.21D0 
  R3LES_LOCAL = 17.502D0
  R4LES_LOCAL = 32.19D0
  
  ! Initialize output
  ZEVAP_OUT(:) = 0.0D0
  
  ! Main computation loop
  DO JL = KIDIA, KFDIA

    ZZRH = RPRECRHMAX + (1.0D0 - RPRECRHMAX) * ZCOVPMAX(JL) / &
           MAX(ZEPSEC, 1.0D0 - ZA(JL))
    ZZRH = MIN(MAX(ZZRH, RPRECRHMAX), 1.0D0)

    ZZRH = MIN(0.8D0, ZZRH)
  
    ZQE = MAX(0.0D0, MIN(ZQX_NCLDQV(JL), ZQSLIQ(JL)))

    LLO1 = ZCOVPCLR(JL) > ZEPSEC .AND. &
           ZQXFG_NCLDQR(JL) > ZEPSEC .AND. & 
           ZQE < ZZRH * ZQSLIQ(JL)

    IF (LLO1) THEN

      ZPRECLR = ZQXFG_NCLDQR(JL) / ZCOVPTOT(JL)
      ZFALLCORR = (RDENSREF / ZRHO(JL))**0.4D0
      ZESATLIQ = RV / RD * R2ES_LOCAL * EXP(R3LES_LOCAL * (ZTP1(JL) - RTT) / (ZTP1(JL) - R4LES_LOCAL))
      ZLAMBDA = (RCL_FAC1 / (ZRHO(JL) * ZPRECLR))**RCL_FAC2

      ZEVAP_DENOM = RCL_CDENOM1 * ZESATLIQ - RCL_CDENOM2 * ZTP1(JL) * ZESATLIQ &
                  + RCL_CDENOM3 * ZTP1(JL)**3 * PAP(JL)
      ZCORR2 = (ZTP1(JL) / 273.0D0)**1.5D0 * 393.0D0 / (ZTP1(JL) + 120.0D0)
      ZKA = RCL_KA273 * ZCORR2

      ZSUBSAT = MAX(ZZRH * ZQSLIQ(JL) - ZQE, 0.0D0)

      ZBETA = (0.5D0 / ZQSLIQ(JL)) * ZTP1(JL)**2 * ZESATLIQ * &
              RCL_CONST1R * (ZCORR2 / ZEVAP_DENOM) * &
              (0.78D0 / (ZLAMBDA**RCL_CONST4R) + &
              RCL_CONST2R * (ZRHO(JL) * ZFALLCORR)**0.5D0 / &
              (ZCORR2**0.5D0 * ZLAMBDA**RCL_CONST3R))
     
      ZDENOM = 1.0D0 + ZBETA * PTSPHY
      ZDPEVAP = ZCOVPCLR(JL) * ZBETA * PTSPHY * ZSUBSAT / ZDENOM

      ZEVAP = MIN(ZDPEVAP, ZQXFG_NCLDQR(JL))
      ZEVAP_OUT(JL) = ZEVAP

      ZSOLQA(JL, NCLDQV, NCLDQR) = ZSOLQA(JL, NCLDQV, NCLDQR) + ZEVAP
      ZSOLQA(JL, NCLDQR, NCLDQV) = ZSOLQA(JL, NCLDQR, NCLDQV) - ZEVAP

      ZCOVPTOT(JL) = MAX(RCOVPMIN, ZCOVPTOT(JL) - MAX(0.0D0, &
                    (ZCOVPTOT(JL) - ZA(JL)) * ZEVAP / ZQXFG_NCLDQR(JL)))

      ZQXFG_NCLDQR(JL) = ZQXFG_NCLDQR(JL) - ZEVAP
    
    ENDIF
  ENDDO
  
END SUBROUTINE rain_evaporation_abel_boutle
