! Saturation Values Calculation
! 

SUBROUTINE compute_saturation_values(KIDIA, KFDIA, KLEV, ZTP1, PAP, &
    & ZFOEALFA, ZFOEEWMT, ZQSMIX, ZFOEEW, ZQSICE, ZFOEELIQT, ZQSLIQ, &
    & RTT, RETV, R2ES, R3LES, R3IES, R4LES, R4IES, RTICE, RTWAT, RTWAT_RTICE_R)

  IMPLICIT NONE
  
  INTEGER, INTENT(IN) :: KIDIA, KFDIA, KLEV
  REAL(8), INTENT(IN) :: ZTP1(KFDIA,KLEV)     
  REAL(8), INTENT(IN) :: PAP(KFDIA,KLEV)   
  
  ! Thermodynamic constants
  REAL(8), INTENT(IN) :: RTT, RETV, R2ES, R3LES, R3IES, R4LES, R4IES
  REAL(8), INTENT(IN) :: RTICE, RTWAT, RTWAT_RTICE_R
  
  ! Output arrays
  REAL(8), INTENT(OUT) :: ZFOEALFA(KFDIA,KLEV)
  REAL(8), INTENT(OUT) :: ZFOEEWMT(KFDIA,KLEV)
  REAL(8), INTENT(OUT) :: ZQSMIX(KFDIA,KLEV)
  REAL(8), INTENT(OUT) :: ZFOEEW(KFDIA,KLEV)
  REAL(8), INTENT(OUT) :: ZQSICE(KFDIA,KLEV)
  REAL(8), INTENT(OUT) :: ZFOEELIQT(KFDIA,KLEV)
  REAL(8), INTENT(OUT) :: ZQSLIQ(KFDIA,KLEV)
  
  ! Local variables
  INTEGER :: JK, JL
  REAL(8) :: ZALFA
  
  ! Statement functions (inlined)
  REAL(8) :: FOEALFA, FOEEWM, FOEDELTA, FOEELIQ, FOEEICE
  REAL(8) :: PTARE
  
  FOEDELTA(PTARE) = MAX(0.0D0, SIGN(1.0D0, PTARE-RTT))
  FOEALFA(PTARE) = MIN(1.0D0, ((MAX(RTICE, MIN(RTWAT, PTARE)) - RTICE) * RTWAT_RTICE_R)**2)
  FOEEWM(PTARE) = R2ES * (FOEALFA(PTARE) * EXP(R3LES*(PTARE-RTT)/(PTARE-R4LES)) + &
                 (1.0D0 - FOEALFA(PTARE)) * EXP(R3IES*(PTARE-RTT)/(PTARE-R4IES)))
  
  FOEELIQ(PTARE) = R2ES * EXP(R3LES*(PTARE-RTT)/(PTARE-R4LES))
  FOEEICE(PTARE) = R2ES * EXP(R3IES*(PTARE-RTT)/(PTARE-R4IES))

  ! Main computation loop
  DO JK = 1, KLEV
    DO JL = KIDIA, KFDIA
      ZFOEALFA(JL,JK) = FOEALFA(ZTP1(JL,JK))
      ZFOEEWMT(JL,JK) = MIN(FOEEWM(ZTP1(JL,JK)) / PAP(JL,JK), 0.5D0)
      ZQSMIX(JL,JK) = ZFOEEWMT(JL,JK)
      ZQSMIX(JL,JK) = ZQSMIX(JL,JK) / (1.0D0 - RETV * ZQSMIX(JL,JK))

      ZALFA = FOEDELTA(ZTP1(JL,JK))
      ZFOEEW(JL,JK) = MIN((ZALFA * FOEELIQ(ZTP1(JL,JK)) + &
                     (1.0D0 - ZALFA) * FOEEICE(ZTP1(JL,JK))) / PAP(JL,JK), 0.5D0)
      ZFOEEW(JL,JK) = MIN(0.5D0, ZFOEEW(JL,JK))
      ZQSICE(JL,JK) = ZFOEEW(JL,JK) / (1.0D0 - RETV * ZFOEEW(JL,JK))

      ZFOEELIQT(JL,JK) = MIN(FOEELIQ(ZTP1(JL,JK)) / PAP(JL,JK), 0.5D0)
      ZQSLIQ(JL,JK) = ZFOEELIQT(JL,JK)
      ZQSLIQ(JL,JK) = ZQSLIQ(JL,JK) / (1.0D0 - RETV * ZQSLIQ(JL,JK))
    ENDDO
  ENDDO

END SUBROUTINE compute_saturation_values
